on: pull_request

name: Pull Requests

jobs:
  message-check:
    name: Block Autosquash Commits

    runs-on: ubuntu-latest

    steps:
      - name: Block Autosquash Commits
        uses: skjnldsv/block-fixup-merge-action@v2

        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
