name: Publish tag to Pypi
on:
  release:
    types: [published]

permissions:
  contents: read #  to fetch code (actions/checkout)


jobs:

  release:
    uses: ./.github/workflows/REUSABLE-wheeler.yaml
    with:
      release: true
    environment: pypi
    permissions:
      id-token: write
    secrets: inherit
