name: Wheel builder

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:

  wheelbuilder:
    uses: ./.github/workflows/REUSABLE-wheeler.yaml
    if: github.event.label.name == 'test-wheels'
    with:
      release: false
    secrets: inherit
